### ISSUE TITLE
Unobtainable item present regardless of filter

### ISSUE THREAD

**Issue by Ju5t-j1m** [CyberGiant7/Elden-Ring-Automatic-Checklist#1]
Regardless of applying the 'Unobtainable' filter the 'ENTWINING UMBILICAL CORD' is still present in the list despite it being currently unobtainable in the vanilla game(patch 1.06). (https://eldenring.wiki.fextralife.com/Entwining+Umbilical+Cord)

![issue1](https://user-images.githubusercontent.com/56307119/192295494-15924c69-76fe-4b62-ae17-5b02cb8aae1c.PNG)

**Comment by CyberGiant7** [comment]
Thank you for you feedback.
That's true, i'll remove it

**Comment by CyberGiant7** [comment]
problem solved
