### ISSUE TITLE
List not updating after 1.12 update

### ISSUE THREAD

**Issue by PokeFrk** [CyberGiant7/Elden-Ring-Automatic-Checklist#16]
1.12 update for Elden Ring seems ot have broken it. It is not reading my save correctly and is showing everything as unobtained.

**Comment by marcellocirelli** [comment]
Confirming this issue can be replicated on my 1.12 save as well

**Comment by CyberGiant7** [comment]
I just tested and the system actually does not work. In the next few weeks, I will take a look at trying to fix the problem. Unfortunately, I don't have much time to manage this project because of college exams

**Comment by timetoea** [comment]
bruv it's the end of june. Exams are not for another month. Get your ass doing the right thing: fixing the free thing we use for our own benefit. College degree is temporary, Elden-Ring-Automatic-Checklist is forever
